### PR TITLE
Tim's page

### PR DESCRIPTION
**Pull request by twood1**

### CODE REVIEW

**Review by cbirger — CHANGES_REQUESTED** [review]
please remove the .jekyll-cache files from the PR

**Comment by twood1** [comment]
Any idea why that would have happened and how to avoid it?

**Comment by cbirger** [comment]
The reason why you picked up all the jekyll cache files is because when you issued the git add command, I'm guessing you didn't explicitly name the files you were adding/updating; instead you issued a blanket "git add" or "git add ." command, which picked up all of the new files in the directory.  We are adding entries in the .gitignore file to avoid this issue in the future.

**Comment by twood1** [comment]
Sounds good - going to fix this today.

**Pull request closed without merging**
